Repository openfun/xblock-configurable-lti-consumer, pull requests merged in 2019-02, with the labels that each got.

#29 🐛(package) fix deprecated pip option
  .circleci/config.yml
  setup.cfg
Labels: bug, needs review

#30 📝(readme) fix installation instructions
  README.md
Labels: easy pick, needs review

#27 ⚡️(iframe) precalculate iframe height to improve user visual feeling
  README.md
  config/settings.yml.dist
  configurable_lti_consumer/configurable_lti_consumer.py
  configurable_lti_consumer/static/js/configurable_xblock_lti_consumer.js
  configurable_lti_consumer/templates/html/student.html
Labels: improvement

#28 Small ux improvements
  configurable_lti_consumer/configurable_lti_consumer.py
Labels: FUN, bug

#31 🔖(patch) bump release to 1.2.0
  CHANGELOG.md
  setup.cfg
Labels: FUN, improvement
