Repository openfun/xblock-configurable-lti-consumer, pull requests merged in 2019-01, with the labels that each got.

#20 🐛(circleci) fix pypi distribution cache key
  .circleci/config.yml
Labels: bug

#22 📦(data) add missing package data
  MANIFEST.in
  setup.cfg
Labels: FUN, bug, critical

#25 🔖(patch) bump release to 1.1.0
  CHANGELOG.md
  setup.cfg
Labels: FUN
